/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/layout`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cadastro` | `/cadastro`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cartScreen` | `/cartScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/orders` | `/orders`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/productsScreen` | `/productsScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/style` | `/style`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/userProfile` | `/userProfile`; params?: Router.UnknownInputParams; } | { pathname: `/utils/auth`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/layout`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/cadastro` | `/cadastro`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/cartScreen` | `/cartScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/orders` | `/orders`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/productsScreen` | `/productsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/style` | `/style`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/userProfile` | `/userProfile`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/auth`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/layout${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/cadastro${`?${string}` | `#${string}` | ''}` | `/cadastro${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/cartScreen${`?${string}` | `#${string}` | ''}` | `/cartScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/orders${`?${string}` | `#${string}` | ''}` | `/orders${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/productsScreen${`?${string}` | `#${string}` | ''}` | `/productsScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/style${`?${string}` | `#${string}` | ''}` | `/style${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/userProfile${`?${string}` | `#${string}` | ''}` | `/userProfile${`?${string}` | `#${string}` | ''}` | `/utils/auth${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/layout`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cadastro` | `/cadastro`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cartScreen` | `/cartScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/orders` | `/orders`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/productsScreen` | `/productsScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/style` | `/style`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/userProfile` | `/userProfile`; params?: Router.UnknownInputParams; } | { pathname: `/utils/auth`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
